# Generated by Django 5.2.3 on 2025-07-13 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_alter_case_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='status_reason',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.casetype'),
        ),
    ]
