# Generated by Django 5.2.3 on 2025-07-29 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status_reason', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='location',
        ),
        migrations.RemoveField(
            model_name='case',
            name='status_reason',
        ),
        migrations.AddField(
            model_name='case',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.status'),
        ),
    ]
