# Generated by Django 5.2.3 on 2025-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0003_casetype_case_status_reason_case_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-updated_at', '-submitted_at']},
        ),
    ]
