# Generated by Django 5.2.3 on 2025-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_status_remove_case_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Police Officer'), ('commander', 'Station Commander')], default='citizen', max_length=20),
        ),
    ]
