# Generated by Django 5.2.3 on 2025-07-30 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
