# Generated by Django 5.2.3 on 2025-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_case_assigned_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_reason',
        ),
        migrations.AddField(
            model_name='case',
            name='status_reason',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
