# Generated by Django 5.2.3 on 2025-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0009_casestatushistory_evidencefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='location_type',
            field=models.CharField(blank=True, choices=[('public_space', 'Public Space'), ('residential_area', 'Residential Area'), ('commercial_area', 'Commercial Area'), ('educational_institution', 'Educational Institution'), ('government_building', 'Government Building'), ('transport_hub', 'Transport Hub'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='suspects_involved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='street_address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
    ]
