# Generated by Django 5.2.3 on 2025-08-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0010_case_landmark_case_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
