# Generated by Django 5.2.3 on 2025-08-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0011_alter_case_city_alter_case_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='category',
            field=models.CharField(blank=True, choices=[('video', 'Video File'), ('audio', 'Audio File'), ('document', 'Document File'), ('image', 'Image File'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.status'),
        ),
    ]
